from __future__ import annotations


def build_issue_title(summary: dict) -> str:
    goal = str(summary.get("goal", "")).strip()
    if goal:
        return f"[自動生成] {goal}"

    in_scope = summary.get("in_scope", [])
    if isinstance(in_scope, list) and in_scope:
        return f"[自動生成] {in_scope[0]}"

    return "[自動生成] 要件整理済みタスク"


def build_issue_body(summary: dict, thread_url: str) -> str:
    background = _format_text(summary.get("background"))
    goal = _format_text(summary.get("goal"))
    in_scope = _format_list(summary.get("in_scope"))
    out_of_scope = _format_list(summary.get("out_of_scope"))
    acceptance = _format_list(summary.get("acceptance_criteria"))
    constraints = _format_list(summary.get("constraints"))
    test_focus = _format_list(summary.get("test_focus"))
    open_questions = _format_list(summary.get("open_questions"))

    return f"""## 背景
{background}

## 目的
{goal}

## やること
{in_scope}

## やらないこと
{out_of_scope}

## 受け入れ条件
{acceptance}

## 制約
{constraints}

## テスト観点
{test_focus}

## 未確定事項
{open_questions}

## 補足
- Discordスレッド: {thread_url}
- Generated by dev-bot
"""


def _format_text(value: object) -> str:
    text = str(value).strip()
    return text or "未記入"


def _format_list(value: object) -> str:
    if not isinstance(value, list) or not value:
        return "- なし"
    return "\n".join(f"- {str(item).strip()}" for item in value if str(item).strip()) or "- なし"
